# Site settings
title: Writing blender-rig-mirror, a Blender Add-on
email: clutterstack@users.noreply.github.com
description: # a > character means to ignore newlines until "baseurl:"
  On the process of writing an add-on for Blender in Python.
baseurl: "/blender-rig-mirror" # the subpath of your site, e.g. /blog/
url: "http://clutterstack.github.io" # the base hostname & protocol for your site
github_username:  clutterstack

# Build settings
markdown: kramdown
